name: My First Workflow

#trigger 
on: [push]

#Jobs in the workflow
jobs:
  my-first-workflow:
    #OS that this job will be running on
    runs-on: ubuntu-latest

    #List of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the contex
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{github.repository_owner}}"
    - name: List runner name
      run: echo "runner os - ${{ runner.os }}"
    - name: Echo my secret
      run: echo "MY_SECRET is ${{ secrets.MY_SECRET }}"
    - name: List
      run: ls -al
    - name: checkout
      uses: actions/checkout@v3
    - name: List
      run: ls -al
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

